### ISSUE TITLE
 Categorical Variables

### ISSUE THREAD

**Issue by jackattackyang** [UBC-MDS/DSCI_522_Pokemon_Legendariness_Classifier#10]
Just finished the draft analysis. 
The biggest issue to watch out for is our data set contains categorical (Types) and numerical values. I generated a new column with 1s and 0s for the categorical variables which is apparently called one-hot encoding in the field. Richie brought up the [same question](https://ubc-mds.slack.com/archives/C24HS41EG/p1542866024090100) on Slack and let's check back for Mike's final take on how to properly handle these.

**Comment by RayceRossum** [comment]
Closed used get_dummies().

Confirmed by @mgelbart

**Comment by mgelbart** [comment]
![image](https://user-images.githubusercontent.com/157368/48924839-6f404c00-ee71-11e8-94d7-6deee6e972ab.png)
