### ISSUE TITLE
Add a tiny bit more detail to your usage instructions

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/DSCI_522_Pokemon_Legendariness_Classifier#39]
I think its always helpful to be extra clear in the usage instructions, so I would suggest that you indicate all the commands you suggest are expected to be run from the root of this project.

**Comment by ttimbers** [comment]
I think its always helpful to be extra clear in the usage instructions, so I would suggest that you indicate all the commands you suggest are expected to be run from the root of this project.

**Comment by jackattackyang** [comment]
Added w/ and w/o Docker instructions, make and run_all as well individual shell scripts
